# Generated by Django 5.2.2 on 2025-06-08 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicodociclo',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='topicodociclo',
            name='topico',
        ),
        migrations.RenameField(
            model_name='edital',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='edital',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='content',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='title',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='content',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='title',
        ),
        migrations.AddField(
            model_name='edital',
            name='texto_original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='titulo',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topico',
            name='descricao',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topico',
            name='revisao1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topico',
            name='revisao2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topico',
            name='revisao3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topico',
            name='revisao4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topico',
            name='revisao5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topico',
            name='revisao6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topico',
            name='teoria_concluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topico',
            name='topico_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopicos', to='edital.topico'),
        ),
        migrations.DeleteModel(
            name='CicloDeEstudo',
        ),
        migrations.DeleteModel(
            name='TopicoDoCiclo',
        ),
    ]
