# Generated by Django 5.2.2 on 2025-06-08 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0002_remove_topicodociclo_ciclo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topico',
            options={'ordering': ['ordem']},
        ),
        migrations.RenameField(
            model_name='edital',
            old_name='titulo',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='texto_original',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='edital',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='revisao1',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='revisao2',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='revisao3',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='revisao4',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='revisao5',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='revisao6',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='teoria_concluida',
        ),
        migrations.RemoveField(
            model_name='topico',
            name='topico_pai',
        ),
        migrations.AddField(
            model_name='edital',
            name='conteudo_bruto',
            field=models.TextField(default=1, help_text='O texto completo colado pelo usuário para referência.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topico',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='edital',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topico',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='edital.edital')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='edital.bloco')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ciclo', to='edital.edital')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to=settings.AUTH_USER_MODEL)),
                ('materias', models.ManyToManyField(related_name='ciclos', to='edital.materia')),
            ],
        ),
        migrations.AddField(
            model_name='topico',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='edital.materia'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teoria', models.BooleanField(default=False)),
                ('revisao1', models.BooleanField(default=False)),
                ('revisao2', models.BooleanField(default=False)),
                ('revisao3', models.BooleanField(default=False)),
                ('revisao4', models.BooleanField(default=False)),
                ('revisao5', models.BooleanField(default=False)),
                ('topico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='edital.topico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
